// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFu7D6tjV_8l09U00gXlo0Y1jLSFodH4',
    appId: '1:323849334771:web:dd02b6cd8471a809356c86',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    authDomain: 'amica-ee087.firebaseapp.com',
    storageBucket: 'amica-ee087.appspot.com',
    measurementId: 'G-SZ36SVC4DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAiakPZYAqGKv9utpY-xUNWkX-t_Hdwi0',
    appId: '1:323849334771:android:ef04421a129d35a5356c86',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    storageBucket: 'amica-ee087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLavLN8Q_-Iq8qbcucZ1N0o1O7xJIcbE',
    appId: '1:323849334771:ios:27c9fade1f361a60356c86',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    storageBucket: 'amica-ee087.appspot.com',
    iosClientId: '323849334771-l6q7c00up16gmu9178n3fc7i5m4rghgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitmom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGLavLN8Q_-Iq8qbcucZ1N0o1O7xJIcbE',
    appId: '1:323849334771:ios:b212bce8fcd476a8356c86',
    messagingSenderId: '323849334771',
    projectId: 'amica-ee087',
    storageBucket: 'amica-ee087.appspot.com',
    iosClientId: '323849334771-7cal46171bj39199jn4n899e0pt93o82.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitmom.RunnerTests',
  );
}
